# Repo: codefoco/AzureDevopsTemplates
resources:
  repositories:
    - repository: templates
      type: github
      name: codefoco/AzureDevopsTemplates
      endpoint: codefoco

pool:
  vmImage: 'ubuntu-16.04'
  demands: msbuild

steps:
- template: common-dotnet.yml@templates

- checkout: self 
  submodules: 'true'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: ChipmunkBinding.sln

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: ChipmunkBinding.Core.sln

# Build .NET 4.5

- task: MSBuild@1
  displayName: 'Build solution ChipmunkBinding.sln'
  inputs:
    solution: ChipmunkBinding.sln
    configuration: Release

# Build .NET Core (to be sure works on Linux)
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ChipmunkBinding.Core.sln'
    arguments: '/p:Configuration=Release'

- task: DotNetCoreCLI@2
  displayName: 'dotnet vstest'
  inputs:
    command: custom
    custom: vstest
    arguments: './tests/build/netcore/bin/Release/netcoreapp3.1/ChipmunkBindingTest.dll'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: libchipmunk.so'
  inputs:
    PathtoPublish: 'runtimes/linux-x64/native/libchipmunk.so'
    ArtifactName: libchipmunk.so

- task: TriggerBuild@3
  displayName: 'Trigger a new build of ChipmunkBinding.Mac'
  inputs:
    buildDefinition: 'ChipmunkBinding.Mac'
    ignoreSslCertificateErrors: true
    useSameSourceVersion: true
    password: '$(myToken)'

- template: send-telegram.yml@templates
