#
# ChipmunkBinding Travis-CI Hook
#

language: csharp

dotnet: 3.1

before_install:
  - export PATH=/opt/mono/bin:$PATH

install:
  - sudo apt-get install mono-devel nunit nuget

script:
  - nuget restore ChipmunkBinding.sln
  - msbuild /p:Configuration=Release /t:Restore ChipmunkBinding.sln
  - msbuild /p:Configuration=Release ChipmunkBinding.sln
  - dotnet test ./tests/build/net45/bin/Release/ChipmunkBindingTest.dll

# Execute additional tests or commands
#after_script:
#  - [run additional test commans]

# Only watch the main branch
branches:
  only:
    - main

# Notify if needed
notifications:
  recipients:
    - viniciusjarina@gmail.com
  email:
    on_success: change
    on_failure: always
